export enum ResponseStatusEnum {
  Success = 0,
  GeneralError = 1,
  NoDataFound = 2,
  InvalidIMEI = 3,
  InvalidSignature = 4,
  InvalidSessionKey = 5,
  InvalidUserOrPassword = 6,
  AccountNotVerified = 7,
  InvalidAccount = 8,
  InvalidRequest = 9,
  InvalidPassword = 10,
  EmailError = 11,
  MetersAssignedBefore = 12,
  MeterAlreadyOnCustomer = 13,
  MeterBelongToAnotherAgent = 14,
  InvalidMeter = 15,
}
