export enum HttpVerb {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  PATCH = 'PATCH',
}

export enum EndPoint {
  AGENTS_LIST = 'agents/list',
  DISTRICTS_LIST = 'Districts/ActiveDistrics/list',
  INSTALLED_METERS = 'meters/installed',
  GET_CONTRACTORS = 'contractors/all',
  GET_Contractors_BY_DISTRICT_ID = 'Districts/Contractors',
  RETIRED_METERS = 'Meters/retired',
  DISTRICTS = 'Districts/all',
  METERS_STATISTICS = 'meters/statistics',
  RETIRED_METER_STATISTICS = 'meters/retired/status/district',
  AGENTS_OPERATIONS_STATISTICS = 'agents/operations/statistics',
  CHANGE_PASSWORD = 'account/ChangePassword',
  GET_AGENTS_BY_CONTRACTOR_ID = 'contractors/{contractorId}/agents',
  MOCK_AGENTS = './mock/agents.mock.json',
  UPDATE_AGENT = 'agents/edit',
  UPDATE_AGENT_STATUS = 'agents/{agentId}/status',
  GET_AGENT_BY_ID = 'agents',
  ADD_AGENT = 'agents/add',
  UPDATE_CONTRACTOR = 'waiting1',
  GET_CONTRACTOR_BY_ID = 'wainting2',
  ADD_CONTRACTOR = 'waiting3',
  INSTALLED_METERS_DETAILS = 'meters/{meterId}/details',
  ASSIGN_METER_TO_AGENT = 'meters/assign-to-contractor',
}
